### PR TITLE
Fix error.stack in nodejs@8

### PR DESCRIPTION
**Pull request by doochik**
https://nodejs.org/dist/latest-v6.x/docs/api/errors.html#errors_error_message
https://nodejs.org/dist/latest-v8.x/docs/api/errors.html#errors_error_message

Changing error.message may not affect error.stack in some cases according to docs.
So ensure that all templates are replaced before log.

### CODE REVIEW

**Comment by Flackus** [comment]
Can you please add node@8 to `.travis.yml` with an according test (if possible)?

**Comment by doochik** [comment]
@Flackus done. I've added nodejs@8 and fix failed test )

**Comment by narqo** [comment]
👍

**Comment by doochik** [comment]
@narqo @Flackus guys, could you release new version?

**Comment by narqo** [comment]
+ terror@1.4.0

**Comment by doochik** [comment]
Thanks a lot!

**Comment by Flackus** [comment]
@doochik thanks!

**Pull request merged**
