### PR TITLE
Terror.isTerror method to check is error instance was "terrorized"

### LINKED ISSUE #22: Terror.isTerror method to check is error instance was "terrorized"
Currently, we have a bunch of `err instanceOf Terror` in our code base. But at the save time, this checks are not prototype safe.

Why not to add a special static method for this job:

~~~js
function Terror() {
  this.__isTerrorized__ = true;
  // ...
}

Terror.isTerror (err) => err.__isTerrorized__
~~~

### PR DESCRIPTION
**Pull request by narqo**
closes #22 

P.S. Will fix the docs before merge

### CODE REVIEW

**Comment by narqo** [comment]
up!

**Comment by kaero** [comment]
Fine

**Comment by kaero** [comment]
@narqo release minor version, plz

**Comment by narqo** [comment]
@kaero I've pushed `package.json` and git-tag, but I don't have permission to publish to npm :(

**Pull request merged**
